#引用注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

#服务端口号
server:
  port: 8003

spring:
  #升级 boot 2.0 后返回日期类型指定为时间戳，实体中jsonFormat自由设置格式
  jackson:
    serialization:
      write-dates-as-timestamps: true
  profiles:
    active: local   #启动默认local的yml配置
  application:
    name: server-call  #该模块的名字
    #文件上传设置大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
